# Generated by Django 4.2.30 on 2026-05-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_chatroom_usermemory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='chat_uploads/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='ChatToolCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('youtube', 'YouTube'), ('image_links', '圖片連結'), ('checklist', '清單')], max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_cards', to='chat.chatmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
