# Generated by Django 4.2.30 on 2026-05-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_inline_media_cards',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allow_memory_summaries',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='response_length',
            field=models.CharField(choices=[('balanced', '剛剛好'), ('short', '短回答'), ('long', '長回答')], default='balanced', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='response_tone',
            field=models.CharField(choices=[('warm', '溫柔陪伴'), ('direct', '直接清楚'), ('reflective', '深入反思')], default='warm', max_length=24),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_theory_basis',
            field=models.BooleanField(default=False),
        ),
    ]
