# Generated by Django 4.2.30 on 2026-05-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_allow_inline_media_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bubble_style',
            field=models.CharField(choices=[('standard', '標準'), ('soft', '柔和圓角'), ('glass', '玻璃感'), ('sharp', '俐落方角')], default='standard', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chat_density',
            field=models.CharField(choices=[('cozy', '舒適'), ('compact', '緊湊'), ('spacious', '寬鬆')], default='cozy', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_accent_color',
            field=models.CharField(default='#188977', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='font_scale',
            field=models.CharField(choices=[('small', '小'), ('normal', '標準'), ('large', '大')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visual_effect',
            field=models.CharField(choices=[('none', '無特效'), ('snow', '雪花'), ('bubbles', '泡泡'), ('rain', '下雨'), ('sunlight', '陽光光影')], default='none', max_length=16),
        ),
    ]
