# Generated by Django 4.2.30 on 2026-05-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_bubble_style_userprofile_chat_density_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cyberpunk_mode',
            field=models.BooleanField(default=False),
        ),
    ]
